"""empty message

Revision ID: 036bc17fc4a6
Revises: 582482be0bd4
Create Date: 2020-10-17 06:06:34.892002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036bc17fc4a6'
down_revision = '582482be0bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('starting_bid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'starting_bid')
    # ### end Alembic commands ###
