"""empty message

Revision ID: 582482be0bd4
Revises: 
Create Date: 2020-10-17 04:57:05.649309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582482be0bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_image', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_image')
    # ### end Alembic commands ###
