"""empty message

Revision ID: 9ad074dde467
Revises: 60eeff45a23d
Create Date: 2020-10-20 01:11:36.375791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad074dde467'
down_revision = '60eeff45a23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bid', 'bid_status',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bid', 'bid_status',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
